name: refresh streamer data

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  getting-data-from-twitch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running script
        env: 
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        run: |
          mkdir exports
          python script.py
          
      - name: push exports to streamer-status branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: streamer-status
          build_dir: exports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
